using System;
using CalamityQOL.Config;
using Terraria;
using Terraria.ID;
using Terraria.Localization;
using Terraria.ModLoader;

namespace CalamityQOL.Recipes;

public class RecipeChanges : ModSystem {
    private int anyCopperBar;
    private int anySilverBar;
    private int anyGoldBar;
    private int anyIceBlock;
    private int anyCobaltBar;
    private int anyEvilPowder;

    public override void AddRecipeGroups() {
        // Sorry, this is needed so the compiler doesn't create a static class from the lambdas
        // which then never gets unloaded.
        int bullshitVariable;
        anyCopperBar = RecipeGroup.RegisterGroup("AnyCopperBar",
            new RecipeGroup(
                () => {
                    bullshitVariable = 0;
                    return Language.GetTextValue("LegacyMisc.37") + " " + Lang.GetItemNameValue(ItemID.CopperBar);
                },
                ItemID.CopperBar, ItemID.TinBar));
        anySilverBar = RecipeGroup.RegisterGroup("AnySilverBar",
            new RecipeGroup(
                () => {
                    bullshitVariable = 0;
                    return Language.GetTextValue("LegacyMisc.37") + " " + Lang.GetItemNameValue(ItemID.SilverBar);
                },
                ItemID.SilverBar, ItemID.TungstenBar));
        anyGoldBar = RecipeGroup.RegisterGroup("AnyGoldBar",
            new RecipeGroup(() => {
                    bullshitVariable = 0;
                    return Language.GetTextValue("LegacyMisc.37") + " " + Lang.GetItemNameValue(ItemID.GoldBar);
                },
                ItemID.GoldBar, ItemID.PlatinumBar));
        anyIceBlock = RecipeGroup.RegisterGroup("AnyIceBlock",
            new RecipeGroup(() => {
                    bullshitVariable = 0;
                    return Language.GetTextValue("LegacyMisc.37") + " " + Lang.GetItemNameValue(ItemID.IceBlock);
                },
                ItemID.IceBlock, ItemID.PurpleIceBlock,
                ItemID.PinkIceBlock, ItemID.RedIceBlock));
        anyCobaltBar = RecipeGroup.RegisterGroup("AnyCobaltBar",
            new RecipeGroup(
                () => Language.GetTextValue("LegacyMisc.37") + " " + Lang.GetItemNameValue(ItemID.CobaltBar),
                ItemID.CobaltBar, ItemID.PalladiumBar));
        anyEvilPowder = RecipeGroup.RegisterGroup("EvilPowder", new RecipeGroup((Func<string>) (() => "Any Evil Powder"), ItemID.VilePowder, ItemID.ViciousPowder));
    }


    public override void AddRecipes() {
        if (!QoLConfig.Instance.accessoryRecipes) {
            return;
        }

        Recipe r1 = Recipe.Create(ItemID.CloudinaBottle, 1);
        r1.AddIngredient(ItemID.Bottle, 1);
        r1.AddIngredient(ItemID.Cloud, 25);
        r1.AddIngredient(ItemID.Feather, 2);
        r1.AddTile(TileID.Anvils);
        r1.Register();
        Recipe r2 = Recipe.Create(ItemID.PortableStool, 1);
        r2.AddRecipeGroup(RecipeGroupID.Wood, 15);
        r2.AddTile(TileID.Sawmill);
        r2.Register();
        Recipe r3 = Recipe.Create(ItemID.HermesBoots, 1);
        r3.AddIngredient(ItemID.Silk, 10);
        r3.AddIngredient(ItemID.SwiftnessPotion, 5);
        r3.AddTile(TileID.Loom);
        r3.Register();
        Recipe r4 = Recipe.Create(ItemID.BlizzardinaBottle, 1);
        r4.AddIngredient(ItemID.Bottle, 1);
        r4.AddIngredient(ItemID.SnowBlock, 50);
        r4.AddIngredient(ItemID.Feather, 3);
        r4.AddTile(TileID.Anvils);
        r4.Register();
        Recipe r5 = Recipe.Create(ItemID.SandstorminaBottle, 1);
        r5.AddIngredient(ItemID.Bottle, 1);
        r5.AddIngredient(ItemID.SandBlock, 70);
        r5.AddIngredient(ItemID.Feather, 3);
        r5.AddTile(TileID.Anvils);
        r5.Register();
        Recipe r6 = Recipe.Create(ItemID.FrogLeg, 1);
        r6.AddIngredient(ItemID.Frog, 6);
        r6.AddTile(TileID.Anvils);
        r6.Register();
        Recipe r7 = Recipe.Create(ItemID.Aglet, 1);
        r7.AddRecipeGroup(anyCopperBar, 5);
        r7.AddTile(TileID.Anvils);
        r7.Register();
        Recipe r8 = Recipe.Create(ItemID.AnkletoftheWind, 1);
        r8.AddIngredient(ItemID.JungleSpores, 15);
        r8.AddIngredient(ItemID.Cloud, 15);
        r8.AddIngredient(ItemID.PinkGel, 5);
        r8.AddTile(TileID.Anvils);
        r8.Register();
        Recipe r9 = Recipe.Create(ItemID.WaterWalkingBoots, 1);
        r9.AddIngredient(ItemID.Leather, 5);
        r9.AddIngredient(ItemID.WaterWalkingPotion, 5);
        r9.AddTile(TileID.Anvils);
        r9.Register();
        Recipe r10 = Recipe.Create(ItemID.FlameWakerBoots, 1);
        r10.AddIngredient(ItemID.Silk, 8);
        r10.AddIngredient(ItemID.Obsidian, 2);
        r10.AddTile(TileID.Loom);
        r10.Register();
        Recipe r11 = Recipe.Create(ItemID.IceSkates, 1);
        r11.AddRecipeGroup(anyIceBlock, 20);
        r11.AddIngredient(ItemID.Leather, 5);
        r11.AddRecipeGroup("IronBar", 5);
        r11.AddTile(TileID.IceMachine);
        r11.Register();
        Recipe r12 = Recipe.Create(ItemID.LuckyHorseshoe, 1);
        r12.AddRecipeGroup(anyGoldBar, 8);
        r12.AddTile(TileID.Anvils);
        r12.Register();
        Recipe r13 = Recipe.Create(ItemID.ShinyRedBalloon, 1);
        r13.AddIngredient(ItemID.WhiteString, 1);
        r13.AddIngredient(ItemID.Gel, 60);
        r13.AddIngredient(ItemID.Cloud, 20);
        r13.AddTile(TileID.Solidifier);
        r13.Register();
        Recipe r14 = Recipe.Create(ItemID.LavaCharm, 1);
        r14.AddIngredient(ItemID.LavaBucket, 3);
        r14.AddIngredient(ItemID.Obsidian, 25);
        r14.AddRecipeGroup(anyGoldBar, 5);
        r14.AddTile(TileID.Anvils);
        r14.Register();
        Recipe r15 = Recipe.Create(ItemID.ObsidianRose, 1);
        r15.AddIngredient(ItemID.JungleRose, 1);
        r15.AddIngredient(ItemID.Obsidian, 10);
        r15.AddIngredient(ItemID.Hellstone, 10);
        r15.AddTile(TileID.Anvils);
        r15.Register();
        Recipe r16 = Recipe.Create(ItemID.FeralClaws, 1);
        r16.AddIngredient(ItemID.Leather, 10);
        r16.AddTile(TileID.Anvils);
        r16.Register();
        Recipe r17 = Recipe.Create(ItemID.Radar, 1);
        r17.AddRecipeGroup("IronBar", 5);
        r17.AddTile(TileID.Anvils);
        r17.Register();
        Recipe r18 = Recipe.Create(ItemID.MetalDetector, 1);
        r18.AddIngredient(ItemID.Wire, 10);
        r18.AddIngredient(ItemID.SpelunkerGlowstick, 5);
        r18.AddRecipeGroup(anyCopperBar, 5);
        r18.AddTile(TileID.Anvils);
        r18.Register();
        Recipe r19 = Recipe.Create(ItemID.DPSMeter, 1);
        r19.AddIngredient(ItemID.Wire, 10);
        r19.AddRecipeGroup(anyGoldBar, 5);
        r19.AddTile(TileID.Anvils);
        r19.Register();
        Recipe r20 = Recipe.Create(ItemID.HandWarmer, 1);
        r20.AddIngredient(ItemID.Silk, 5);
        r20.AddIngredient(ItemID.Shiverthorn, 1);
        r20.AddIngredient(ItemID.SnowBlock, 10);
        r20.AddTile(TileID.Loom);
        r20.Register();
        Recipe r21 = Recipe.Create(ItemID.FlowerBoots, 1);
        r21.AddIngredient(ItemID.Silk, 7);
        r21.AddIngredient(ItemID.JungleRose, 1);
        r21.AddIngredient(ItemID.JungleGrassSeeds, 5);
        r21.AddTile(TileID.Loom);
        r21.Register();
        Recipe r22 = Recipe.Create(ItemID.BandofRegeneration, 1);
        r22.AddIngredient(ItemID.Shackle, 1);
        r22.AddIngredient(ItemID.LifeCrystal, 1);
        r22.AddTile(TileID.Anvils);
        r22.Register();
        Recipe r23 = Recipe.Create(ItemID.ShoeSpikes, 1);
        r23.AddRecipeGroup("IronBar", 5);
        r23.AddIngredient(ItemID.Spike, 10);
        r23.AddTile(TileID.Anvils);
        r23.Register();
        Recipe r24 = Recipe.Create(ItemID.FlareGun, 1);
        r24.AddRecipeGroup(anyCopperBar, 5);
        r24.AddIngredient(ItemID.Torch, 10);
        r24.AddTile(TileID.Anvils);
        r24.Register();

        Recipe r25 = Recipe.Create(ItemID.CobaltShield, 1);
        r25.AddRecipeGroup(anyCobaltBar, 10);
        r25.AddTile(TileID.Anvils);
        r25.Register();
        Recipe r26 = Recipe.Create(ItemID.ArmorPolish, 1);
        r26.AddIngredient(ItemID.Bone, 50);
        r26.AddTile(TileID.Anvils);
        r26.Register();
        Recipe r27 = Recipe.Create(ItemID.AdhesiveBandage, 1);
        r27.AddIngredient(ItemID.Silk, 10);
        r27.AddIngredient(ItemID.Gel, 50);
        r27.AddIngredient(ItemID.HealingPotion, 1);
        r27.AddTile(TileID.Anvils);
        r27.Register();
        Recipe r28 = Recipe.Create(ItemID.Bezoar, 1);
        r28.AddIngredient(ItemID.Stinger, 15);
        r28.AddTile(TileID.Anvils);
        r28.Register();
        Recipe r29 = Recipe.Create(ItemID.Nazar, 1);
        r29.AddIngredient(ItemID.SoulofNight, 15);
        r29.AddIngredient(ItemID.Lens, 3);
        r29.AddTile(TileID.Anvils);
        r29.Register();
        Recipe r30 = Recipe.Create(ItemID.Vitamins, 1);
        r30.AddIngredient(ItemID.BottledWater, 1);
        r30.AddIngredient(ItemID.Waterleaf, 5);
        r30.AddIngredient(ItemID.Blinkroot, 5);
        r30.AddIngredient(ItemID.Daybloom, 5);
        r30.AddTile(TileID.Anvils);
        r30.Register();
        Recipe r31 = Recipe.Create(ItemID.Blindfold, 1);
        r31.AddIngredient(ItemID.Silk, 30);
        r31.AddIngredient(ItemID.TatteredCloth, 3);
        r31.AddTile(TileID.Anvils);
        r31.Register();
        Recipe r32 = Recipe.Create(ItemID.TrifoldMap, 1);
        r32.AddIngredient(ItemID.Silk, 20);
        r32.AddIngredient(ItemID.SoulofLight, 3);
        r32.AddIngredient(ItemID.SoulofNight, 3);
        r32.AddTile(TileID.Anvils);
        r32.Register();
        Recipe r33 = Recipe.Create(ItemID.FastClock, 1);
        r33.AddIngredient(ItemID.Timer1Second, 1);
        r33.AddIngredient(ItemID.PixieDust, 15);
        r33.AddIngredient(ItemID.SoulofLight, 5);
        r33.AddTile(TileID.Anvils);
        r33.Register();
        Recipe r34 = Recipe.Create(ItemID.Megaphone, 1);
        r34.AddIngredient(ItemID.Wire, 10);
        r34.AddRecipeGroup(anyCobaltBar, 5);
        r34.AddIngredient(ItemID.Ruby, 3);
        r34.AddTile(TileID.Anvils);
        r34.Register();
        Recipe r35 = Recipe.Create(ItemID.PocketMirror, 1);
        r35.AddIngredient(ItemID.Glass, 10);
        r35.AddRecipeGroup(anyGoldBar, 4);
        r35.AddIngredient(ItemID.CrystalShard, 2);
        r35.AddIngredient(ItemID.SoulofNight, 2);
        r35.AddTile(TileID.Anvils);
        r35.Register();

        Recipe r36 = Recipe.Create(ItemID.CelestialMagnet, 1);
        r36.AddIngredient(ItemID.TreasureMagnet, 1);
        r36.AddIngredient(ItemID.FallenStar, 5);
        r36.AddTile(TileID.Anvils);
        r36.Register();
        Recipe r37 = Recipe.Create(ItemID.FrozenTurtleShell, 1);
        r37.AddIngredient(ItemID.TurtleShell, 3);
        r37.AddTile(TileID.IceMachine);
        r37.Register();
        Recipe r38 = Recipe.Create(ItemID.MagicQuiver, 1);
        r38.AddIngredient(ItemID.EndlessQuiver, 1);
        r38.AddIngredient(ItemID.PixieDust, 10);
        r38.AddIngredient(ItemID.Lens, 5);
        r38.AddIngredient(ItemID.SoulofLight, 8);
        r38.AddTile(TileID.CrystalBall);
        r38.Register();
        Recipe r39 = Recipe.Create(ItemID.PulseBow, 1);
        r39.AddIngredient(ItemID.ShroomiteBar, 16);
        r39.AddTile(TileID.MythrilAnvil);
        r39.Register();
        Recipe r40 = Recipe.Create(ItemID.BouncingShield, 1);
        r40.AddRecipeGroup(anyCobaltBar, 12);
        r40.AddIngredient(ItemID.SoulofLight, 4);
        r40.AddTile(TileID.Anvils);
        r40.Register();
        Recipe r41 = Recipe.Create(ItemID.MechanicalGlove, 1);
        r41.AddIngredient(ItemID.PowerGlove, 1);
        r41.AddIngredient(ItemID.WarriorEmblem, 1);
        r41.AddIngredient(ItemID.SoulofFright, 1);
        r41.AddIngredient(ItemID.SoulofMight, 1);
        r41.AddIngredient(ItemID.SoulofSight, 1);
        r41.Register();
        Recipe r42 = Recipe.Create(ItemID.CelestialEmblem, 1);
        r42.AddIngredient(ItemID.CelestialMagnet, 1);
        r42.AddIngredient(ItemID.SorcererEmblem, 1);
        r42.AddIngredient(ItemID.SoulofFright, 1);
        r42.AddIngredient(ItemID.SoulofMight, 1);
        r42.AddIngredient(ItemID.SoulofSight, 1);
        r42.Register();

        Recipe r43 = Recipe.Create(ItemID.EskimoHood, 1);
        r43.AddIngredient(ItemID.Silk, 4);
        r43.AddIngredient(ItemID.Leather, 1);
        r43.AddIngredient(ItemID.BorealWood, 12);
        r43.AddTile(TileID.Loom);
        r43.Register();
        Recipe r44 = Recipe.Create(ItemID.EskimoCoat, 1);
        r44.AddIngredient(ItemID.Silk, 8);
        r44.AddIngredient(ItemID.Leather, 1);
        r44.AddIngredient(ItemID.BorealWood, 18);
        r44.AddTile(TileID.Loom);
        r44.Register();
        Recipe r45 = Recipe.Create(ItemID.EskimoPants, 1);
        r45.AddIngredient(ItemID.Silk, 6);
        r45.AddIngredient(ItemID.Leather, 1);
        r45.AddIngredient(ItemID.BorealWood, 15);
        r45.AddTile(TileID.Loom);
        r45.Register();
        Recipe r46 = Recipe.Create(ItemID.PharaohsMask, 1);
        r46.AddIngredient(ItemID.AncientCloth, 3);
        r46.AddTile(TileID.Loom);
        r46.Register();
        Recipe r47 = Recipe.Create(ItemID.PharaohsRobe, 1);
        r47.AddIngredient(ItemID.AncientCloth, 4);
        r47.AddTile(TileID.Loom);
        r47.Register();

        Recipe r48 = Recipe.Create(ItemID.Shuriken, 50);
        r48.AddRecipeGroup("IronBar", 1);
        r48.AddTile(TileID.Anvils);
        r48.Register();
        Recipe r49 = Recipe.Create(ItemID.ThrowingKnife, 50);
        r49.AddRecipeGroup("IronBar", 1);
        r49.AddTile(TileID.Anvils);
        r49.Register();
        Recipe r50 = Recipe.Create(ItemID.WoodenBoomerang, 1);
        r50.AddIngredient(9, 7);
        r50.AddTile(18);
        r50.Register();
        Recipe r51 = Recipe.Create(ItemID.WandofSparking, 1);
        r51.AddIngredient(ItemID.Wood, 5);
        r51.AddIngredient(ItemID.Torch, 3);
        r51.AddIngredient(ItemID.FallenStar, 1);
        r51.AddTile(TileID.Anvils);
        r51.Register();
        Recipe r52 = Recipe.Create(ItemID.BabyBirdStaff, 1);
        r52.AddIngredient(ItemID.Bird, 1);
        r52.AddRecipeGroup("Wood", 8);
        r52.AddTile(TileID.WorkBenches);
        r52.Register();
        Recipe r53 = Recipe.Create(ItemID.Starfury, 1);
        r53.AddIngredient(ItemID.GoldBroadsword, 1);
        r53.AddIngredient(ItemID.FallenStar, 10);
        r53.AddTile(TileID.Anvils);
        r53.Register();
        Recipe r54 = Recipe.Create(ItemID.Starfury, 1);
        r54.AddIngredient(ItemID.PlatinumBroadsword, 1);
        r54.AddIngredient(ItemID.FallenStar, 10);
        r54.AddTile(TileID.Anvils);
        r54.Register();
        Recipe r55 = Recipe.Create(ItemID.EnchantedBoomerang, 1);
        r55.AddIngredient(ItemID.WoodenBoomerang, 1);
        r55.AddRecipeGroup(anyGoldBar, 8);
        r55.AddTile(TileID.Anvils);
        r55.Register();
        Recipe r56 = Recipe.Create(ItemID.EnchantedSword, 1);
        r56.AddRecipeGroup(anyGoldBar, 12);
        r56.AddIngredient(ItemID.Diamond, 1);
        r56.AddIngredient(ItemID.Ruby, 1);
        r56.AddTile(TileID.Anvils);
        r56.Register();
        // Where is Recipe 57? You'll have to find out
        Recipe r58 = Recipe.Create(ItemID.WaterBolt, 1);
        r58.AddIngredient(ItemID.SpellTome, 1);
        r58.AddIngredient(ItemID.Waterleaf, 3);
        r58.AddIngredient(ItemID.WaterCandle, 1);
        r58.AddTile(TileID.Bookcases);
        r58.Register();
        Recipe r59 = Recipe.Create(ItemID.SlimeStaff, 1);
        r59.AddRecipeGroup("Wood", 6);
        r59.AddIngredient(ItemID.Gel, 40);
        r59.AddTile(TileID.Anvils);
        r59.Register();
        Recipe r60 = Recipe.Create(ItemID.IceBoomerang, 1);
        r60.AddIngredient(ItemID.WoodenBoomerang, 1);
        r60.AddRecipeGroup(anyIceBlock, 20);
        r60.AddIngredient(ItemID.SnowBlock, 10);
        r60.AddIngredient(ItemID.Shiverthorn, 1);
        r60.AddTile(TileID.IceMachine);
        r60.Register();

        Recipe r61 = Recipe.Create(ItemID.GuideVoodooDoll, 1);
        r61.AddIngredient(ItemID.Leather, 2);
        r61.AddRecipeGroup(anyEvilPowder, 10);
        r61.AddTile(TileID.Hellforge);
        r61.Register();
        Recipe r62 = Recipe.Create(ItemID.SnowGlobe, 1);
        r62.AddIngredient(ItemID.SnowBlock, 50);
        r62.AddIngredient(ItemID.Glass, 10);
        r62.AddIngredient(ItemID.SoulofLight, 3);
        r62.AddIngredient(ItemID.SoulofNight, 3);
        r62.AddTile(TileID.Anvils);
        r62.Register();
        Recipe r63 = Recipe.Create(ItemID.QueenSlimeCrystal, 1);
        r63.AddIngredient(ItemID.CrystalShard, 20);
        r63.AddIngredient(ItemID.PinkGel, 10);
        r63.AddIngredient(ItemID.SoulofLight, 5);
        r63.AddTile(TileID.Solidifier);
        r63.Register();
        Recipe r64 = Recipe.Create(ItemID.TempleKey, 1);
        r64.AddIngredient(ItemID.JungleSpores, 15);
        r64.AddIngredient(ItemID.RichMahogany, 15);
        r64.AddIngredient(ItemID.SoulofLight, 15);
        r64.AddIngredient(ItemID.SoulofNight, 15);
        r64.AddTile(TileID.MythrilAnvil);
        r64.Register();
        Recipe r65 = Recipe.Create(ItemID.LihzahrdPowerCell, 1);
        r65.AddIngredient(ItemID.LihzahrdBrick, 15);
        r65.AddTile(TileID.LihzahrdFurnace);
        r65.Register();

        Recipe r66 = Recipe.Create(ItemID.Umbrella, 1);
        r66.AddIngredient(ItemID.Silk, 5);
        r66.AddRecipeGroup(anyCopperBar, 2);
        r66.AddTile(TileID.Loom);
        r66.Register();
        Recipe r67 = Recipe.Create(ItemID.BugNet, 1);
        r67.AddIngredient(ItemID.Cobweb, 30);
        r67.AddRecipeGroup(anyCopperBar, 3);
        r67.AddTile(TileID.Anvils);
        r67.Register();
        Recipe r68 = Recipe.Create(ItemID.MagicMirror, 1);
        r68.AddRecipeGroup(anySilverBar, 10);
        r68.AddIngredient(ItemID.Glass, 10);
        r68.AddIngredient(ItemID.FallenStar, 10);
        r68.AddTile(TileID.Anvils);
        r68.Register();
        Recipe r69 = Recipe.Create(ItemID.IceMirror, 1);
        r69.AddRecipeGroup(anySilverBar, 5);
        r69.AddRecipeGroup(anyIceBlock, 20);
        r69.AddIngredient(ItemID.Glass, 10);
        r69.AddIngredient(ItemID.FallenStar, 10);
        r69.AddTile(TileID.Anvils);
        r69.Register();
        Recipe r70 = Recipe.Create(ItemID.BloodMoonStarter, 1);
        r70.AddRecipeGroup(anyCopperBar, 20);
        r70.AddTile(TileID.Anvils);
        r70.Register();
        Recipe r71 = Recipe.Create(ItemID.StaffofRegrowth, 1);
        r71.AddIngredient(ItemID.RichMahogany, 10);
        r71.AddIngredient(ItemID.JungleSpores, 5);
        r71.AddIngredient(ItemID.JungleRose, 1);
        r71.AddTile(TileID.WorkBenches);
        r71.Register();
        Recipe r72 = Recipe.Create(ItemID.ShadowKey, 1);
        r72.AddIngredient(ItemID.GoldenKey, 1);
        r72.AddIngredient(ItemID.Obsidian, 20);
        r72.AddIngredient(ItemID.Bone, 5);
        r72.AddTile(TileID.Anvils);
        r72.Register();
        Recipe r73 = Recipe.Create(ItemID.SkyMill, 1);
        r73.AddIngredient(ItemID.SunplateBlock, 10);
        r73.AddIngredient(ItemID.Cloud, 5);
        r73.AddIngredient(ItemID.RainCloud, 3);
        r73.AddTile(TileID.Anvils);
        r73.Register();
        Recipe r74 = Recipe.Create(2198, 1);
        r74.AddRecipeGroup(anyIceBlock, 25);
        r74.AddIngredient(ItemID.SnowBlock, 15);
        r74.AddRecipeGroup("IronBar", 3);
        r74.AddTile(TileID.Anvils);
        r74.Register();
        Recipe r75 = Recipe.Create(ItemID.CatBast, 1);
        r75.AddRecipeGroup("IronBar", 7);
        r75.AddRecipeGroup(anyGoldBar, 3);
        r75.AddIngredient(ItemID.Ruby, 1);
        r75.AddTile(TileID.Anvils);
        r75.Register();
        Recipe r76 = Recipe.Create(ItemID.EncumberingStone, 1);
        r76.AddIngredient(ItemID.StoneBlock, 100);
        r76.AddTile(TileID.Anvils);
        r76.Register();
        Recipe r77 = Recipe.Create(ItemID.DesertMinecart, 1);
        r77.AddIngredient(ItemID.SandstoneBrick, 20);
        r77.AddRecipeGroup(anyGoldBar, 6);
        r77.AddRecipeGroup("IronBar", 3);
        r77.AddTile(TileID.Anvils);
        r77.Register();
        
        //Alt. Leather
        Recipe r78 = Recipe.Create(ItemID.Leather, 1);
        r78.AddIngredient(ItemID.Vertebrae, 5);
        r78.AddTile(TileID.WorkBenches);
        r78.Register();
    }
}